wandb_version: 1

datset:
  desc: null
  value:
    USZ:
      raw:
        path_to_tof_dir: /scratch_net/biwidl319/jbermeo/data/raw/USZ
        fp_pattern_tof:
        - '*'
        - '*_tof.nii.gz'
        path_to_seg_dir: /scratch_net/biwidl319/jbermeo/data/raw/USZ
        fp_pattern_seg_mask:
        - '*'
        - '*_seg.nii.gz'
        every_scan_has_seg: true
        level_of_dir_with_id: -2
      preprocessed:
        paths_processed: /scratch_net/biwidl319/jbermeo/data/preprocessed/USZ/1_resampled
        paths_original: /scratch_net/biwidl319/jbermeo/data/raw/USZ
    ADAM:
      raw:
        path_to_tof_dir: /scratch_net/biwidl319/jbermeo/data/raw/ADAM
        fp_pattern_tof:
        - '*'
        - '*_TOF.nii.gz'
        path_to_seg_dir: /scratch_net/biwidl319/jbermeo/data/raw/ADAM
        fp_pattern_seg_mask:
        - '*'
        - '*_aneurysms.nii.gz'
        every_scan_has_seg: true
        level_of_dir_with_id: -2
      preprocessed:
        paths_processed: /scratch_net/biwidl319/jbermeo/data/preprocessed/ADAM/1_resampled
        paths_original: /scratch_net/biwidl319/jbermeo/data/raw/ADAM
    Lausanne:
      raw:
        path_to_tof_dir: /scratch_net/biwidl319/jbermeo/data/raw/Lausanne/original_images
        fp_pattern_tof:
        - '*'
        - '*'
        - '*'
        - '*_angio.nii.gz'
        path_to_seg_dir: /scratch_net/biwidl319/jbermeo/data/raw/Lausanne/skull_stripped_and_aneurysm_mask
        fp_pattern_seg_mask:
        - '*'
        - '*'
        - '*'
        - '*Lesion_1_mask.nii.gz'
        every_scan_has_seg: false
        level_of_dir_with_id: -4
      preprocessed:
        paths_processed: /scratch_net/biwidl319/jbermeo/data/preprocessed/Lausanne/5_h5
        paths_original: /scratch_net/biwidl319/jbermeo/data/raw/Lausanne
    hcp_t1:
      n_classes: 15
      resolution_proc:
      - 0.7
      - 0.7
      - 0.7
      dim:
      - 256
      - 256
      - 256
      paths_processed:
        train: /scratch_net/biwidl319/jbermeo/data/HCP/preprocessed/T1/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_from_0_to_20.hdf5
        test: /scratch_net/biwidl319/jbermeo/data/HCP/preprocessed/T1/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_from_50_to_70.hdf5
        val: /scratch_net/biwidl319/jbermeo/data/HCP/preprocessed/T1/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_from_20_to_25.hdf5
      paths_original:
        train: /scratch_net/biwidl319/jbermeo/data/HCP/preprocessed/T1/data_T1_original_depth_256_from_0_to_20.hdf5
        test: /scratch_net/biwidl319/jbermeo/data/HCP/preprocessed/T1/data_T1_original_depth_256_from_50_to_70.hdf5
        val: /scratch_net/biwidl319/jbermeo/data/HCP/preprocessed/T1/data_T1_original_depth_256_from_20_to_25.hdf5
model:
  desc: null
  value:
    dae:
      n_classes: 15
      channel_size:
      - 16
      - 32
      - 64
      channels_bottleneck: 128
      skips:
      - false
      - true
      - true
      n_dimensions: 3
training:
  desc: null
  value:
    wandb_log: true
    seed: 0
    resume: false
    device: cuda
    checkpoint_best: checkpoint_best.pth
    checkpoint_last: checkpoint_last.pth
    dae:
      wandb_project: ma-domain-generalization-dae
      logdir: /scratch_net/biwidl319/jbermeo/logs/brain/dae/hcp_t1
      batch_size: 1
      num_workers: 3
      dataset: hcp_t1
      n_classes: 21
      image_size:
      - 256
      - 256
      - 256
      rescale_factor:
      - 0.25
      - 1
      - 1
      epochs: 2500
      validate_every: 50
      learning_rate: 0.001
      validation_set_multiplier: 50
      augmentation:
        da_ratio: 0.25
        sigma: 20
        alpha: 1000
        trans_min: -10
        trans_max: 10
        rot_min: -10
        rot_max: 10
        scale_min: 0.9
        scale_max: 1.1
        gamma_min: 1.0
        gamma_max: 1.0
        brightness_min: 0.0
        brightness_max: 0.0
        noise_mean: 0.0
        noise_std: 0.0
      deformation:
        mask_type: squares_jigsaw
        mask_radius: 10
        mask_squares: 200
        is_num_masks_fixed: false
        is_size_masks_fixed: false
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705666764.16033
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 3
      - 5
      - 14
      - 16
      - 23
      4: 3.9.18
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
