
seed: 0
device:           cuda
dataset:          hcp_t2
splits:           [train, val, test] 

batch_size: 16
num_workers: 3
image_size: [1, 256, 256]

logdir: $RESULTS_DIR/brain/preprocessing/hcp_t2

normalize_with_nn:   
  augmentation: null

  model:
    checkpoint: $RESULTS_DIR/brain/hcp_t1/bg_supp/checkpoint_best.pth
    activation: rbf
    batch_norm: true
    channel_size: 16
    image_channels: 1
    kernel_size: 3
    n_layers: 3
    residual: true
    n_dimensions: 2


precalculate_dino_features:

  dino_model: large
  
  hierarchy_level: 2

  augmentation:
    num_epochs: 20

    sigma:              20
    alpha:              1000
    trans_min:          -10
    trans_max:          10
    rot_min:            -10
    rot_max:            10
    scale_min:          0.9
    scale_max:          1.1
    gamma_min:          0.5 #0.2     # Default 0.5
    gamma_max:          2.0 #5.0     # Default 2.0
    brightness_min:     0.0 #-0.2    # Default 0.0
    brightness_max:     0.1 #0.2     # Default 0.1
    noise_mean:         0.0
    noise_std:          0.1

