wandb_log:        True
start_new_exp:    False
seed:             0
resume:           False
device:           cuda
checkpoint_best:  checkpoint_best.pth
checkpoint_last:  checkpoint_last.pth
dataset:          umc           # brain: hcp_t1, hcp_t2, abide_caltech, abide_stanford;
                                # wmh: umc, nuhs, vu
                                # wmh + synthseg labels: umc_w_synthseg_labels, nuhs_w_synthseg_labels, vu_w_synthseg_labels

dae:
  wandb_project:                mt-dae_training
  batch_size:                   1
  num_workers:                  3
  image_size:                   [48, 256, 256]    # [256, 256, 256] for brain, [48, 256, 256] for wmh
  rescale_factor:               [1, 1, 1]         # [0.25, 1, 1] for brain, [1, 1, 1] for wmh
  epochs:                       5000              # 2500 for brain (hcp_t1, hcp_t2), 5000 for brain (abide_caltech) and WMH (nuhs, umc, vu)
  validate_every:               100               # 50 for brain (hcp_t1, hcp_t2), 100 for brain (abide_caltech) and WMH (nuhs, umc, vu)
  learning_rate:                1.0e-3
  validation_set_multiplier:    50
  logdir:                       /scratch_net/biwidl319/jbermeo/logs/wmh/dae/debugging/umc/test_run

  # Loss function parameters
  epsilon:                      1e-10
  smooth:                       0
  fg_only:                      False 
  
  augmentation:
    da_ratio:             0.25
    sigma:                20
    alpha:                1000
    trans_min:            -10
    trans_max:            10
    rot_min:              -10
    rot_max:              10
    scale_min:            0.9
    scale_max:            1.1
    gamma_min:            1.0
    gamma_max:            1.0
    brightness_min:       0.0
    brightness_max:       0.0
    noise_mean:           0.0
    noise_std:            0.0
  
  deformation:
    mask_type:            squares_jigsaw # zeros / random_labels / jigsaw
    mask_radius:          10 # The mask will be a square with side length twice this number 
    mask_squares:         200
    is_num_masks_fixed:   False
    is_size_masks_fixed:  False

segmentation:
  batch_size:                   16
  num_workers:                  3
  image_size:                   [1, 256, 256]
  epochs:                       1000  # 150 for brain, 1000 for WMH (nuhs, umc)
  validate_every:               3
  learning_rate:                0.001
  logdir:                       /scratch_net/biwidl319/jbermeo/data/models/wmh/umc/no_bg_supp_norm_w_3x3_conv_v2
  wandb_project:                mt-segmentation_models
  
  with_bg_supression:           False

  # Loss function parameters
  epsilon:                      1e-10
  smooth:                       0
  debug_mode:                   False
  fg_only:                      False  

  bg_suppression_opts:
    type:               none  # possible values: none, fixed_value, random_value
    bg_value:           -0.5
    bg_value_min:       -0.5
    bg_value_max:       1
    mask_source:        thresholding  # possible values: thresholding, ground_truth
    thresholding:       otsu  # possible values: isodata, li, mean, minimum, otsu, triangle, yen
    hole_filling:       True
  
  augmentation:
    da_ratio:           0.25
    sigma:              20
    alpha:              1000
    trans_min:          -10
    trans_max:          10
    rot_min:            -10
    rot_max:            10
    scale_min:          0.9
    scale_max:          1.1
    gamma_min:          0.5     # Default 0.5
    gamma_max:          2.0     # Default 2.0
    brightness_min:     0.0     # Default 0.0
    brightness_max:     0.1     # Default 0.1
    noise_mean:         0.0
    noise_std:          0.1


segmentation_dino:
  dino_model:                   large  # small, base, large, gigantic
  svd_path:                     null
  
  precalculated_fts:            False

  optimizer_type:               adam # adam, adamW
  
  epochs:                       150  # 150 for subcortical_structures, 1000 for WMH (nuhs, umc)
  batch_size:                   16
  num_workers:                  2
  validate_every:               3
  learning_rate:                0.001
  warmup_steps:                 null # 0.05 for 5% of the total number of steps
  logdir:                       $RESULTS_DIR/subcortical_structures/segmentation/hcp_t1/dino_seg/debug
  wandb_project:                mt-segmentation_models

  image_size:                   [1, 256, 256]
  with_bg_supression:           False

  # Loss function parameters
  epsilon:                      1e-10
  smooth:                       0
  debug_mode:                   False
  fg_only:                      False  

  bg_suppression_opts:
    type:               none  # possible values: none, fixed_value, random_value, None means no background suppression
    bg_value:           -0.5
    bg_value_min:       -0.5
    bg_value_max:       1
    mask_source:        thresholding  # possible values: thresholding, ground_truth
    thresholding:       otsu  # possible values: isodata, li, mean, minimum, otsu, triangle, yen
    hole_filling:       True
  
  augmentation:
    da_ratio:           0.25
    sigma:              20
    alpha:              1000
    trans_min:          -10
    trans_max:          10
    rot_min:            -10
    rot_max:            10
    scale_min:          0.9
    scale_max:          1.1
    gamma_min:          0.5 #0.2     # Default 0.5
    gamma_max:          2.0 #5.0     # Default 2.0
    brightness_min:     0.0 #-0.2    # Default 0.0
    brightness_max:     0.1 #0.2     # Default 0.1
    noise_mean:         0.0
    noise_std:          0.1
    

ddpm:
  batch_size:                   2
  gradient_accumulate_every:    64
  num_workers:                  3
  norm_with_nn_on_fly:          True
  use_original_imgs:            False
  one_hot_encode:               True
  normalize:                    min_max
  norm_q_range:                 [0.001, 0.999]
  image_size:                   [1, 256, 256]
  rescale_factor:               [1, 1, 1]
  condition_by_mult:            False
  also_unconditional:           False
  only_unconditional:           False
  unconditional_rate:           0.2
  class_weighing:               'none'      # 'none', 'balanced', 'custom'
  classes_of_interest:          null        # Lesion class is 16 for WMH + synthseg labels, otherwise it is 1 
  clip_classes_of_interest_at_factor: null  # null for no clipping, or 10. It is maximum ratio between weight of the class of interest and the weight of the other classes excluding the background

  objective:                    pred_v      # default is pred_v
  learning_rate:                8e-5        # 1e-4 in the constructor
  amp:                          True
  train_num_steps:              75000       # btw 12,500 and 50,000
  timesteps:                    1000        # Range of noising steps to sample from during training. 1000 in the constructor  
  sampling_timesteps:           100         # Number of sampling steps to generate images. If less than 1000, will use DDIM sampling. If null, will be the same as timesteps => linear denoising steps
  save_and_sample_every:        2500        # 1000 in the constructor 
  num_validation_samples:       100         # Num of images to sample to check performance during training
  num_viz_samples:              50          # Must have an interger square root to store images in a square grid
  log_val_loss_every:           250

  logdir:                       /scratch_net/biwidl319/jbermeo/logs/wmh/umc/ddpm/normalized_imgs/3x3_norm_filters/3_18/batch_size_128_cond_by_concat
  wandb_project:                mt-ddpm
  
  norm_dir:                     /scratch_net/biwidl319/jbermeo/data/models/wmh/segmentation/umc_w_synthseg_labels/no_bg_supp_norm_w_3x3
  load_best_cpt:                True
  
  augmentation:                 
    da_ratio:           0.25
    sigma:              20
    alpha:              1000
    trans_min:          -10
    trans_max:          10
    rot_min:            -10
    rot_max:            10
    scale_min:          0.9
    scale_max:          1.1
    gamma_min:          0.5     # Default 0.5
    gamma_max:          2.0     # Default 2.0
    brightness_min:     0.0     # Default 0.0
    brightness_max:     0.1     # Default 0.1
    noise_mean:         0.0
    noise_std:          0.0

  bg_suppression_opts:          null
  deformation:                  null

