wandb_log:        True
seed:             0
resume:           True
device:           cuda
checkpoint_best:  checkpoint_best.pth
checkpoint_last:  checkpoint_last.pth

dae:
  wandb_project:                mt-tta-dae
  logdir:                       logs/dae
  batch_size:                   1
  num_workers:                  3
  dataset:                      hcp_t1            # brain: hcp_t1, hcp_t2, abide_caltech, abide_stanford; wmh: nuhs, umc, vu
  n_classes:                    21                # 1 for brain, 2 for wmh
  image_size:                   [256, 256, 256]   # [256, 256, 256] for brain, [48, 256, 256] for wmh
  rescale_factor:               [0.25, 1, 1]      # [0.25, 1, 1] for brain, [1, 1, 1] for wmh
  epochs:                       2500              # 2500 for brain (hcp_t1, hcp_t2), 5000 for brain (abide_caltech) and WMH (nuhs, umc, vu)
  validate_every:               50                # 50 for brain (hcp_t1, hcp_t2), 100 for brain (abide_caltech) and WMH (nuhs, umc, vu)
  learning_rate:                1.0e-3
  validation_set_multiplier:    50
  logdir:                       logs/brain/dae/hcp_t1
  wandb_project:                ma-domain-generalization-dae
  
  augmentation:
    da_ratio:             0.25
    sigma:                20
    alpha:                1000
    trans_min:            -10
    trans_max:            10
    rot_min:              -10
    rot_max:              10
    scale_min:            0.9
    scale_max:            1.1
    gamma_min:            1.0
    gamma_max:            1.0
    brightness_min:       0.0
    brightness_max:       0.0
    noise_mean:           0.0
    noise_std:            0.0
  
  deformation:
    mask_type:            squares_jigsaw # zeros / random_labels / jigsaw
    mask_radius:          10 # The mask will be a square with side length twice this number 
    mask_squares:         200
    is_num_masks_fixed:   False
    is_size_masks_fixed:  False