tta_mode: dae_and_diffusion # no_tta, gnn, gt, dae, dae_and_diffusion

start_new_exp: True
wandb_log: True

dataset: nuhs      # brain: hcp_t1, hcp_t2, abide_caltech, abide_stanford; wmh: nuhs, umc, vu
split:   val      # val, test
image_size: [1, 256, 256]
start: null       # Index of the test dataset to start at
stop:  null       # Index of the test dataset to stop at

seg_dir: /scratch_net/biwidl319/jbermeo/data/models/wmh/segmentation/umc/no_bg_supp_norm_w_3x3_conv
load_best_cpt: True

num_workers: 0
device: cuda
seed: 0

bg_suppression_opts:
  type: none  # possible values: none, fixed_value, random_value
  bg_value: -0.5
  bg_value_min: -0.5
  bg_value_max: 1
  mask_source: thresholding  # possible values: thresholding, ground_truth
  thresholding: otsu  # possible values: isodata, li, mean, minimum, otsu, triangle, yen
  hole_filling: True

dae:
  wandb_project: mt-tta-wmh
  logdir: /scratch_net/biwidl319/jbermeo/logs/wmh/tta/tests/3_20/dae_only
  dae_dir: /scratch_net/biwidl319/jbermeo/data/models/wmh/dae/umc
  
  seg_with_bg_supp: False

  accumulate_over_volume: True
  batch_size: 16
  dataset_repetition: 1
  num_steps: 1000  # 500 for brain, 2700 for wmh
  update_dae_output_every: 25
  calculate_dice_every: 25  # 25 for brain, 135 for wmh (nuhs, umc, vu)
  alpha: 1.0
  beta: 0.25
  learning_rate: 0.001
  save_checkpoints: True
  const_aug_per_volume: False
  
  bg_suppression_opts:
    type: none  # possible values: none, fixed_value, random_value
    bg_value: -0.5
    bg_value_min: -0.5
    bg_value_max: 1
    mask_source: thresholding  # possible values: thresholding, ground_truth
    thresholding: otsu  # possible values: isodata, li, mean, minimum, otsu, triangle, yen
    hole_filling: True
  
  augmentation:
    da_ratio: 0.25
    sigma: 20
    alpha: 0
    trans_min: 0
    trans_max: 0
    rot_min: 0
    rot_max: 0
    scale_min: 1.0
    scale_max: 1.0
    gamma_min: 0.5
    gamma_max: 2.0
    brightness_min: 0.0
    brightness_max: 0.1
    noise_mean: 0.0
    noise_std: 0.1


dae_and_ddpm:
  wandb_project: mt-tta-wmh
  logdir: /scratch_net/biwidl319/jbermeo/logs/wmh/tta/dae_and_cddpm/3_22/
  dae_dir: /scratch_net/biwidl319/jbermeo/data/models/wmh/dae/umc
  ddpm_dir: /scratch_net/biwidl319/jbermeo/logs/wmh/ddpm/normalized_imgs/no_bg_supp_3x3_conv/3_19/batch_size_128_cond_by_concat_multi_gpu
  cpt_fn: 'model-19.pt' 

  seg_with_bg_supp: False

  ddpm_loss_beta: 1.0
  dae_loss_alpha: 1.0
  ddpm_sample_guidance_eta: 0.0

  use_ddpm_after_step: null # 500
  use_ddpm_after_dice: 0.5 # 0.5
  warmup_steps_for_ddpm_loss: 100
  minibatch_size_ddpm: 2
  frac_vol_diffusion_tta: 1.0
  min_t_diffusion_tta: 0
  max_t_diffusion_tta: 999
  sampling_timesteps: 100
  min_max_int_norm_imgs: [-0.6761907935142517, 1.2947211265563965]
  use_x_norm_for_ddpm_loss: True
  use_y_pred_for_ddpm_loss: True
  use_x_cond_gt: False    # Only true for debugging

  accumulate_over_volume: True
  batch_size: 16
  dataset_repetition: 2
  num_steps: 2700  # 500 for brain, 2700 for wmh
  update_dae_output_every: 135 # 68 on the final results params reported by nico
  calculate_dice_every: 135  # 25 for brain, 135 for wmh (nuhs, umc, vu), on the documented repo
  alpha: 1.0
  beta: 0.25 
  use_atlas_only_for_init: False
  learning_rate: 0.001
  save_checkpoints: True
  const_aug_per_volume: False
  
  bg_suppression_opts:
    type: none  # possible values: none, fixed_value, random_value
    bg_value: -0.5
    bg_value_min: -0.5
    bg_value_max: 1
    mask_source: thresholding  # possible values: thresholding, ground_truth
    thresholding: otsu  # possible values: isodata, li, mean, minimum, otsu, triangle, yen
    hole_filling: True
  
  augmentation:
    da_ratio: 0.25
    sigma: 20
    alpha: 0
    trans_min: 0
    trans_max: 0
    rot_min: 0
    rot_max: 0
    scale_min: 1.0
    scale_max: 1.0
    gamma_min: 0.5
    gamma_max: 2.0
    brightness_min: 0.0
    brightness_max: 0.1
    noise_mean: 0.0
    noise_std: 0.0 # 0.1 in the original implementation from Nico

diffusion_tta:
  wandb_project: mt-tta-diffusion_tta-tests
  logdir: /scratch_net/biwidl319/jbermeo/logs/brain/sota/diffusion_tta/tests/original_algo
  ddpm_dir: /scratch_net/biwidl319/jbermeo/logs/brain/ddpm/original_imgs/not_one_hot_64_base_filters_with_aug_except_noise
  cpt_fn: 'model-9.pt' # or 23, 28, or 31

  original_algo: True
  batch_size: 4
  minibatch_size_ddpm: 2
  batch_size_ddpm: 1 #180 # 180 for original algo
  num_steps:  1 # 5   # 5 for original algo
  
  learning_rate: 0.00001
  learning_rate_norm: null # If null, takes the same value as learning_rate
  learning_rate_seg: null  # If null, takes the same value as learning_rate
  learning_rate_ddpm: null # If null, takes the same value as learning_rate

  fit_norm_params: True
  fit_seg_params: True
  fit_ddpm_params: True

  frac_vol_diffusion_tta: 0.25
  min_t_diffusion_tta: 0
  max_t_diffusion_tta: 1000
  sampling_timesteps: 100
  min_max_int_norm_imgs: [0, 1]
  
  calculate_dice_every: 25  # 25 for brain, 135 for wmh (nuhs, umc, vu)
  accumulate_over_volume: False
  save_checkpoints: True
  const_aug_per_volume: False
  
  bg_suppression_opts:
    type: fixed_value  # possible values: none, fixed_value, random_value
    bg_value: -0.5
    bg_value_min: -0.5
    bg_value_max: 1
    mask_source: thresholding  # possible values: thresholding, ground_truth
    thresholding: otsu  # possible values: isodata, li, mean, minimum, otsu, triangle, yen
    hole_filling: True
  
  augmentation:
    da_ratio: 0.25
    sigma: 20
    alpha: 0
    trans_min: 0
    trans_max: 0
    rot_min: 0
    rot_max: 0
    scale_min: 1.0
    scale_max: 1.0
    gamma_min: 0.5
    gamma_max: 2.0
    brightness_min: 0.0
    brightness_max: 0.1
    noise_mean: 0.0
    noise_std: 0.0