USZ:
  label_names_dict:       '/scratch_net/biwidl319/jbermeo/data/raw/USZ/label_names_dict.json'
  raw:
    path_to_tof_dir:      '/scratch_net/biwidl319/jbermeo/data/raw/USZ'
    fp_pattern_tof:       ['*', '*_tof.nii.gz']
    
    path_to_seg_dir:      '/scratch_net/biwidl319/jbermeo/data/raw/USZ'
    fp_pattern_seg_mask:  ['*', '*_seg.nii.gz']
    every_scan_has_seg:   True
    level_of_dir_with_id: -2

  preprocessed:
    h5_filepath:          '/scratch_net/biwidl319/jbermeo/data/preprocessed/UIA_segmentation/USZ.h5'
  
  original:
    h5_filepath:          '/scratch_net/biwidl319/jbermeo/data/raw/USZ'
      

ADAM:
  label_names_dict:       '/scratch_net/biwidl319/jbermeo/data/raw/ADAM/label_names_dict.json'
  raw:
    path_to_tof_dir:      '/scratch_net/biwidl319/jbermeo/data/raw/ADAM'
    fp_pattern_tof:       ['*', '*_TOF.nii.gz']
    
    path_to_seg_dir:      '/scratch_net/biwidl319/jbermeo/data/raw/ADAM'
    fp_pattern_seg_mask:  ['*', '*_aneurysms.nii.gz']
    every_scan_has_seg:   True
    level_of_dir_with_id: -2

  preprocessed:
    h5_filepath:          '/scratch_net/biwidl319/jbermeo/data/preprocessed/UIA_segmentation/ADAM.h5'
  
  original:
    h5_filepath:          '/scratch_net/biwidl319/jbermeo/data/raw/ADAM'



Lausanne:
  label_names_dict:       '/scratch_net/biwidl319/jbermeo/data/raw/Lausanne/label_names_dict.json'

  raw:
    path_to_tof_dir:     '/scratch_net/biwidl319/jbermeo/data/raw/Lausanne/original_images'
    fp_pattern_tof:      ['*', '*', '*', '*_angio.nii.gz']
    
    path_to_seg_dir:     '/scratch_net/biwidl319/jbermeo/data/raw/Lausanne/skull_stripped_and_aneurysm_mask'
    fp_pattern_seg_mask: ['*', '*', '*', '*Lesion_*_mask.nii.gz']
    every_scan_has_seg:   False
    level_of_dir_with_id: -4

  preprocessed:
    h5_filepath:          '/scratch_net/biwidl319/jbermeo/data/preprocessed/UIA_segmentation/Lausanne.h5'
  
  original:
    h5_filepath:          '/scratch_net/biwidl319/jbermeo/data/raw/Lausanne'



hcp_t1:
  image_channels: 1
  n_classes: 15
  resolution_proc: [0.7, 0.7, 0.7]  # voxel size of processed dataset in [mm] (xyz)
  dim: [256, 256, 256]  # DHW (= zxy)
  paths_processed:
    train: /scratch_net/biwidl319/jbermeo/data/hcp/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_from_0_to_20.hdf5
    test: /scratch_net/biwidl319/jbermeo/data/hcp/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_from_50_to_70.hdf5
    val: /scratch_net/biwidl319/jbermeo/data/hcp/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_from_20_to_25.hdf5
  
  paths_normalized_with_nn:
    train: /scratch_net/biwidl319/jbermeo/logs/brain/preprocessing/hcp_t1/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_from_0_to_20.hdf_normalized_with_nn.h5
    test: /scratch_net/biwidl319/jbermeo/logs/brain/preprocessing/hcp_t1/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_from_50_to_70.hdf_normalized_with_nn.h5
    val: /scratch_net/biwidl319/jbermeo/logs/brain/preprocessing/hcp_t1/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_from_20_to_25.hdf_normalized_with_nn.h5

  paths_original:
    train: /scratch_net/biwidl319/jbermeo/data/hcp/data_T1_original_depth_256_from_0_to_20.hdf5
    test: /scratch_net/biwidl319/jbermeo/data/hcp/data_T1_original_depth_256_from_50_to_70.hdf5
    val: /scratch_net/biwidl319/jbermeo/data/hcp/data_T1_original_depth_256_from_20_to_25.hdf5


hcp_t2:
  image_channels: 1
  n_classes: 15
  resolution_proc: [0.7, 0.7, 0.7]  # voxel size of processed dataset in [mm] (xyz)
  dim: [256, 256, 256]  # DHW (= zxy)
  paths_processed:
    train: /scratch_net/biwidl319/jbermeo/data/hcp/data_T2_2d_size_256_256_depth_256_res_0.7_0.7_from_0_to_20.hdf5
    test: /scratch_net/biwidl319/jbermeo/data/hcp/data_T2_2d_size_256_256_depth_256_res_0.7_0.7_from_50_to_70.hdf5
    val: /scratch_net/biwidl319/jbermeo/data/hcp/data_T2_2d_size_256_256_depth_256_res_0.7_0.7_from_20_to_25.hdf5
  paths_normalized_with_nn:
    train: /scratch_net/biwidl319/jbermeo/logs/brain/preprocessing/hcp_t2/data_T2_2d_size_256_256_depth_256_res_0.7_0.7_from_0_to_20.hdf_normalized_with_nn.h5
    test: /scratch_net/biwidl319/jbermeo/logs/brain/preprocessing/hcp_t2/data_T2_2d_size_256_256_depth_256_res_0.7_0.7_from_50_to_70.hdf_normalized_with_nn.h5
    val: /scratch_net/biwidl319/jbermeo/logs/brain/preprocessing/hcp_t2/data_T2_2d_size_256_256_depth_256_res_0.7_0.7_from_20_to_25.hdf_normalized_with_nn.h5
  paths_original:
    train: /scratch_net/biwidl319/jbermeo/data/hcp/data_T2_original_depth_256_from_0_to_20.hdf5
    test: /scratch_net/biwidl319/jbermeo/data/hcp/data_T2_original_depth_256_from_50_to_70.hdf5
    val: /scratch_net/biwidl319/jbermeo/data/hcp/data_T2_original_depth_256_from_50_to_70.hdf5


abide_caltech:
  image_channels: 1
  n_classes: 15
  resolution_proc: [0.7, 0.7, 0.7]  # voxel size of processed dataset in [mm] (xyz)
  dim: [256, 256, 256]  # DHW (= zxy)
  paths_processed:
    train: /scratch_net/biwidl319/jbermeo/data/abide/caltech/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_0.7_from_0_to_10.hdf5
    test: /scratch_net/biwidl319/jbermeo/data/abide/caltech/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_0.7_from_16_to_36.hdf5
    val: /scratch_net/biwidl319/jbermeo/data/abide/caltech/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_0.7_from_10_to_15.hdf5
  paths_normalized_with_nn:
    train: /scratch_net/biwidl319/jbermeo/logs/brain/preprocessing/abide_caltech/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_0.7_from_0_to_10.hdf_normalized_with_nn.h5
    test: /scratch_net/biwidl319/jbermeo/logs/brain/preprocessing/abide_caltech/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_0.7_from_16_to_36.hdf5
    val: /scratch_net/biwidl319/jbermeo/logs/brain/preprocessing/abide_caltech/data_T1_2d_size_256_256_depth_256_res_0.7_0.7_0.7_from_10_to_15.hdf5
  paths_original:
    train: /scratch_net/biwidl319/jbermeo/data/abide/caltech/data_T1_original_depth_256_from_0_to_10.hdf5
    test: /scratch_net/biwidl319/jbermeo/data/abide/caltech/data_T1_original_depth_256_from_16_to_36.hdf5
    val: /scratch_net/biwidl319/jbermeo/data/abide/caltech/data_T1_original_depth_256_from_10_to_15.hdf5

abide_stanford:
  image_channels: 1
  n_classes: 15
  resolution_proc: [0.7, 0.7, 0.7]  # voxel size of processed dataset in [mm] (xyz)
  dim: [132, 256, 256]  # DHW (= zxy)
  paths_processed:
      train: ~/datasets/abide/stanford/data_T1_2d_size_256_256_depth_132_res_0.7_0.7_from_0_to_10.hdf5
      test: ~/datasets/abide/stanford/data_T1_2d_size_256_256_depth_132_res_0.7_0.7_from_16_to_36.hdf5
      val: ~/datasets/abide/stanford/data_T1_2d_size_256_256_depth_132_res_0.7_0.7_from_10_to_15.hdf5
  paths_original:
      train: ~/datasets/abide/stanford/data_T1_original_depth_132_from_0_to_10.hdf5
      test: ~/datasets/abide/stanford/data_T1_original_depth_132_from_16_to_36.hdf5
      val: ~/datasets/abide/stanford/data_T1_original_depth_132_from_10_to_15.hdf5

nuhs:
  n_classes: 2
  resolution_proc: [1, 1, 3]  # in-plane resolution of processed dataset
  dim: [48, 256, 256]  # DHW (= zxy)
  paths_processed:
      train: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/nuhs/data_nuhs_2d_size_256_256_depth_48_res_1_1_3_from_0_to_10.hdf5
      test: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/nuhs/data_nuhs_2d_size_256_256_depth_48_res_1_1_3_from_10_to_15.hdf5
      val: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/nuhs/data_nuhs_2d_size_256_256_depth_48_res_1_1_3_from_15_to_20.hdf5
  paths_original:
      train: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/nuhs/data_nuhs_original_depth_-1_from_0_to_10.hdf5
      test: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/nuhs/data_nuhs_original_depth_-1_from_10_to_15.hdf5
      val: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/nuhs/data_nuhs_original_depth_-1_from_15_to_20.hdf5

umc:
  image_channels: 1
  n_classes: 2
  resolution_proc: [1, 1, 3]  # in-plane resolution of processed dataset
  dim: [48, 256, 256]  # DHW (= zxy)
  paths_processed:
      train: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/umc/data_umc_2d_size_256_256_depth_48_res_1_1_3_from_0_to_10.hdf5
      test: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/umc/data_umc_2d_size_256_256_depth_48_res_1_1_3_from_10_to_15.hdf5
      val: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/umc/data_umc_2d_size_256_256_depth_48_res_1_1_3_from_15_to_20.hdf5
  paths_original:
      train: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/umc/data_umc_original_depth_-1_from_0_to_10.hdf5
      test: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/umc/data_umc_original_depth_-1_from_10_to_15.hdf5
      val: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/umc/data_umc_original_depth_-1_from_15_to_20.hdf5

vu:
  image_channels: 1
  n_classes: 2
  resolution_proc: [1, 1, 3]  # in-plane resolution of processed dataset
  dim: [48, 256, 256]  # DHW (= zxy)
  paths_processed:
      train: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/vu/data_vu_2d_size_256_256_depth_48_res_1_1_3_from_0_to_10.hdf5
      test: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/vu/data_vu_2d_size_256_256_depth_48_res_1_1_3_from_10_to_15.hdf5
      val: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/vu/data_vu_2d_size_256_256_depth_48_res_1_1_3_from_15_to_20.hdf5
  paths_original:
      train: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/vu/data_vu_original_depth_-1_from_0_to_10.hdf5
      test: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/vu/data_vu_original_depth_-1_from_10_to_15.hdf5
      val: /scratch_net/biwidl319/jbermeo/data/wmh_miccai/vu/data_vu_original_depth_-1_from_15_to_20.hdf5
