USZ:
  raw:
    path_to_tof_dir:      '/scratch_net/biwidl319/jbermeo/data/raw/USZ'
    fp_pattern_tof:       ['*', '*_tof.nii.gz']
    
    path_to_seg_dir:      '/scratch_net/biwidl319/jbermeo/data/raw/USZ'
    fp_pattern_seg_mask:  ['*', '*_seg.nii.gz']
    every_scan_has_seg:   True
    level_of_dir_with_id: -2
      

ADAM:
  raw:
    path_to_tof_dir:      '/scratch_net/biwidl319/jbermeo/data/raw/ADAM'
    fp_pattern_tof:       ['*', '*_TOF.nii.gz']
    
    path_to_seg_dir:      '/scratch_net/biwidl319/jbermeo/data/raw/ADAM'
    fp_pattern_seg_mask:  ['*', '*_aneurysms.nii.gz']
    every_scan_has_seg:   True
    level_of_dir_with_id: -2

Lausanne:
  raw:
    path_to_tof_dir:     '/scratch_net/biwidl319/jbermeo/data/raw/Lausanne/original_images'
    fp_pattern_tof:      ['*', '*', '*', '*_angio.nii.gz']
    
    path_to_seg_dir:     '/scratch_net/biwidl319/jbermeo/data/raw/Lausanne/skull_stripped_and_aneurysm_mask'
    fp_pattern_seg_mask: ['*', '*', '*', '*Lesion_1_mask.nii.gz']
    every_scan_has_seg:   False
    level_of_dir_with_id: -4