imdae:
  channel_size:                     [16, 32, 64]
  channels_bottleneck:              128
  skips:                            [False, True, True]
  n_dimensions:                     3


normalization_2D:
  n_layers:                         3
  image_channels:                   1
  channel_size:                     16
  kernel_size:                      3
  activation:                       rbf
  batch_norm:                       True
  residual:                         True

segmentation_2D:
  image_channels:                   1
  channel_size:                     [16, 32, 64]
  channels_bottleneck:              128
  skips:                            [True, True, True]
  n_dimensions:                     2

normalization_3D:
  n_layers:                         3
  image_channels:                   1
  channel_size:                     16
  kernel_size:                      3
  activation:                       rbf
  batch_norm:                       True
  residual:                         True

segmentation_3D:
  image_channels:                   1
  channel_size:                     [16, 32, 64]
  channels_bottleneck:              128
  skips:                            [True, True, True]
  n_dimensions:                     3