wandb_log: True
dataset: hcp_t2   # brain: hcp_t1, hcp_t2, abide_caltech, abide_stanford; wmh: nuhs, umc, vu
start: null       # Index of the test dataset to start at
stop:  null       # Index of the test dataset to stop at
num_workers: 0
device: cuda
tta_mode: dae # no_tta, gnn, gt
image_size: [1, 256, 256]
seed: 0

bg_suppression_opts:
  type: fixed_value  # possible values: none, fixed_value, random_value
  bg_value: -0.5
  bg_value_min: -0.5
  bg_value_max: 1
  mask_source: thresholding  # possible values: thresholding, ground_truth
  thresholding: otsu  # possible values: isodata, li, mean, minimum, otsu, triangle, yen
  hole_filling: True

dae:
  wandb_project: mt-tta-dae-dae_tta
  logdir: /scratch_net/biwidl319/jbermeo/logs/brain/sota/dae/hcp_t1_bg_supp
  dae_dir: /scratch_net/biwidl319/jbermeo/data/previous_results_nico/logs/brain/dae/hcp_t1
  seg_dir: /scratch_net/biwidl319/jbermeo/data/previous_results_nico/logs/brain/segmentation/hcp_t1_bg_supp
  batch_size: 16
  dataset_repetition: 1
  num_steps: 500  # 500 for brain, 2700 for wmh
  update_dae_output_every: 25
  calculate_dice_every: 25  # 25 for brain, 135 for wmh (nuhs, umc, vu)
  alpha: 1.0
  beta: 0.25
  learning_rate: 1.0e-2
  save_checkpoints: True
  const_aug_per_volume: False
  accumulate_over_volume: True
  bg_suppression_opts:
      type: fixed_value  # possible values: none, fixed_value, random_value
      bg_value: -0.5
      bg_value_min: -0.5
      bg_value_max: 1
      mask_source: thresholding  # possible values: thresholding, ground_truth
      thresholding: otsu  # possible values: isodata, li, mean, minimum, otsu, triangle, yen
      hole_filling: True
  augmentation:
      da_ratio: 0.25
      sigma: 20
      alpha: 0
      trans_min: 0
      trans_max: 0
      rot_min: 0
      rot_max: 0
      scale_min: 1.0
      scale_max: 1.0
      gamma_min: 0.5
      gamma_max: 2.0
      brightness_min: 0.0
      brightness_max: 0.1
      noise_mean: 0.0
      noise_std: 0.1